language: cpp

arch:
  - arm64
  - amd64

os:
  - linux

dist:
  - bionic

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
      - sourceline: "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic-updates main universe"
    packages:
      - clang-10
      - gcc-10
      - g++-10

before_install:
  - sudo apt-get install -y build-essential
  - sh .ci/cross-tool.sh

install:
  # /usr/bin/{gcc,clang} points to an older compiler on Ubuntu Linux.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-10" CC="gcc-10"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-10" CC="clang-10"; fi

script:
  - make check
  - sh .ci/cross-check.sh

jobs:
  include:
    - stage: Coding convention check
      arch: amd64
      compiler: gcc
      before_install: sudo apt-get install -y clang-format
      script: sh .ci/check-format.sh
